name: Build and Deploy Application JAR

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    name: 'Build and Upload to S3'
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out your repository code
    - name: Checkout
      uses: actions/checkout@v4

    # Step 2: Set up Java Development Kit (JDK)
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Step 3: Build the application with Maven
    - name: Build with Maven
      # Assuming your pom.xml is in the root of the repo
      # If it's in a subfolder, change the working-directory
      run: mvn -B package --file pom.xml

    # Step 4: Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Step 5: Upload JAR to S3
    - name: Upload JAR to S3 Bucket
      run: |
        # Find the JAR file in the target directory
        JAR_FILE=$(find target -name "*.jar" | head -n 1)
        if [ -f "$JAR_FILE" ]; then
          aws s3 cp $JAR_FILE s3://${{ secrets.JAR_BUCKET_NAME }}/
          echo "Successfully uploaded $JAR_FILE to s3://${{ secrets.JAR_BUCKET_NAME }}/"
        else
          echo "Error: JAR file not found."
          exit 1
        fi